//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteque.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotEntities : DbContext
    {
        public bibliotEntities()
            : base("name=bibliotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTEUR> AUTEUR { get; set; }
        public virtual DbSet<courant_litteraire> courant_litteraire { get; set; }
        public virtual DbSet<EDITE> EDITE { get; set; }
        public virtual DbSet<EDITEUR> EDITEUR { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<livre> livre { get; set; }
    }
}
