//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDITE
    {
        public int id_livre { get; set; }
        public int id_editeur { get; set; }
        public string isbn { get; set; }
        public System.DateTime date_edition { get; set; }
    
        public virtual EDITEUR EDITEUR { get; set; }
        public virtual livre livre { get; set; }
    }
}
