//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livre()
        {
            this.EDITE = new HashSet<EDITE>();
        }
    
        public int id_livre { get; set; }
        public string nom_livre { get; set; }
        public int id_genre { get; set; }
        public int id_auteur { get; set; }
    
        public virtual AUTEUR AUTEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDITE> EDITE { get; set; }
        public virtual genre genre { get; set; }
    }
}
